config/routes.rb
Rails.application.routes.draw do
  root "pokedex#index"
  get "/pokedex" =>"pokedex#index"
  get "/" =>"pokedex#index"
  
  get "pokedex/viewEntry" => "pokedex#viewEntry"
  get "pokedex/viewPC" => "pokedex#viewPC"
  get "pokedex/findPokemon" => "pokedex#findPokemon"
  get "pokedex/viewAllPokemon"=> "pokedex#viewAllPokemon"
  
  get "pokedex/viewEntry"
  get "pokedex/viewPC"
  get "pokedex/viewAllPokemon"
  
  get "pokemons/viewMyPokemon"
  get "pokemons/viewMyShiny"
  get "pokemons/viewNotCaught"
  get "pokemons/findPokemon"
  
  
  post "/" => "pokedex#viewEntry"
  post "/" => "pokedex#viewPC"
  post "/" => "pokedex#viewAllPokemon"
  post "pokedex/viewEntry" => "pokedex#viewEntry"
  
  resources :pokemons

end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pokedex_controller.rb
require 'open-uri'
class PokedexController < ApplicationController
  def index
    puts "--index--"
  end

  
  def viewPC
     puts "--------viewPC--------"
     #
  end


  def viewEntry
    puts "--------In view Pokemon--------"
    number = params[:numberInput]
    entry = {"Number" => number}
    @pokemons = Pokemon.all
    for i in @pokemons do
      if i.Number == number.to_i
        File.open('justForPassing.txt', 'w') {|file| file.truncate(0) }
        f = File.open("justForPassing.txt", "w") 
        f.write(i.Name)
        f.close()
        respond_to do |format|
          format.html {redirect_to "/pokemons/findPokemon"}
        end
      end
    end
  end
  
  
  def viewAllPokemon
    puts "--------In view all Pokemon--------"
    @allPokemon = []
    page = open("http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_National_Pok%C3%A9dex_number").read
    page_body = page.scan(/(<img.alt=..*?")/).flatten
    stringMarker1 = "<img alt=\""
    page_body.each do |i|
        inList = false
        i = i.remove("<img alt=\"")
        i = i.chomp("\"")
        @allPokemon.each do |k|
          if k == i
            inList = true
          end
        end
        @allPokemon.push(i) if inList == false
    end
    @allPokemon.push("Kote")
    f = File.open('allPokemon.txt', 'w') 
    @allPokemon.each do |j|
      f.write(j)
      f.write("\n")
    end
    f.close()
   end 
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemons
  # GET /pokemons.json
  def index
    @myPokemon = []
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
    @photo = "gray.jpg"
    if @pokemon.Name == "kote" or @pokemon.Name == "Kote"
      @photo = "surprise.jpg"
    else
      @photo = "gray.jpg"
    end
    
  end
 
  
  def viewMyPokemon
    @myPokemon = []
    @pokemons = Pokemon.all
    @pokemons.each do |i|
       if i.Caught
         @myPokemon.push(i)
       end
     end
  end
   
  def viewMyShiny
    @myShinyPokemon = []
    @pokemons = Pokemon.all
    @pokemons.each do |i|
       if i.Shiny
         @myShinyPokemon.push(i)
       end
     end
  end
  
  def viewNotCaught
    @notMyPokemon = []
    @pokemons = Pokemon.all
    @pokemons.each do |i|
       if i.Caught == false
         @notMyPokemon.push(i)
       end
     end
  end
  
  def findPokemon
    puts "----- find pokemon------"
    @poke = File.read("justForPassing.txt")
    @allPokemon = File.read("allPokemon.txt")
    @allPokemon = @allPokemon.split("\n")
    @pokemonList = []
    @allPokemon.each do |x|
      @pokemonList.push(x)
    end
    @pokemons = Pokemon.all
    @pokemons.each do |x|
      if x.Name == @poke
        @pokemon = x
      end
    end
  end
  
  
  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    realPokemon = false 
    @pokemon = Pokemon.new(pokemon_params)
    @allPokemon = File.read("allPokemon.txt")
    @pokemonList = @allPokemon.split("\n")
    @pokemonList.each do |x|
      if x == @pokemon.Name
        realPokemon = true
      end
    end
    respond_to do |format| 
      if realPokemon == false
        format.html { redirect_to @pokemon, notice: 'Pokémon could not be created; not a valid Pokémon'}
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      elsif @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokémon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      @allPokemon = File.read("allPokemon.txt")
      @pokemonList = @allPokemon.split("\n")
      realPokemon = false
      @pokemonList.each do |x|
      if x == pokemon_params[:Name]
        realPokemon = true
        end
      end
      if realPokemon == false
        format.html { redirect_to @pokemon, notice: 'Pokémon could not be updated; not a valid Pokémon'}
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      elsif @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokémon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit}
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokémon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
  
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.require(:pokemon).permit(:Number, :Name, :Type, :Level, :Ability, :Height, :Weight, :Gender, :Caught, :Location_Caught, :Level_Caught, :Shiny, :PC, :Can_Evolve)
    end      
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokedex_helper.rb
module PokedexHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokedex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pokedex/index.html.erb
<body style="background-color: lightgray;">
<center><h1><%= image_tag "pokeballg.gif"%>Welcome to Cory's Pokedex<%= image_tag "masterball.gif"%></h1></center>
<center><%= form_tag do%>
	<br></br>
	<form><a href=/pokemons/new><button type="button" style="background-color:red; font-size:15px"><b>Add Pokémon</b></button ></a></form>
	<br></br>
	<form><a href=/pokedex/viewPC><button type="button" style="background-color:black; color:white; font-size:15px"><b>View PC</b></button ></a></form>
	<br></br>
	<form><a href=/pokedex/viewEntry><button type="button" style="background-color:white; font-size:15px" ><b>View Pokémon Entry</b></button ></a></form>
	<br></br>
	<br></br>
	<form><a href=/pokedex/viewAllPokemon><button type="button" style="background-color:purple; color:white; font-size:15px" ><b>View all valid Pokemon</b></button ></a></form>
	<br></br>
	<form><a href=http://www.serebii.net><button type="button" style="background-color:black; color:white; font-size:15px" ><b>Learn more about pokemon!</b></button ></a></form>
	<br></br>
	<form><a href=/pokemons><button type="button" style="background-color:white; font-size:15px" ><b>Your current pokemon database</b></button ></a></form>

<%end%></center>
</body>

app/views/pokedex/viewAllPokemon.html.erb
<body style="background-color: lightgray;">
<p id="notice"><%= notice %></p>

<div align="right"><form><a href=/pokedex><button type="button" style="background-color:white; font-size:15px" ><b>Main Menu</b></button ></a></form></div>


<center><h1>All Pokemon </h3></center>

<table>
  <thead>
    <tr>
      <th> Number </th>
      <th> Name </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%@allPokemon.each_with_index do |x, index|%>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= x %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<div align="right"><form><a href=/pokedex><button type="button" style="background-color:white; font-size:15px" ><b>Main Menu</b></button ></a></form></div>

app/views/pokedex/viewEntry.html.erb
<body style="background-color: lightgray;">
<h3>Please write which pokemon you would like:</h3>

<%= form_tag do%>
	<p>Number: <%= text_field_tag(:numberInput)%> </p>
	<p><%= submit_tag "Enter Number"%> </p>
<%end%>

<div align="left"><%= image_tag "dragonite.gif"%><%= image_tag "ash.jpeg"%>
<br></br>
<br></br>
<br></br>
<div align="right"><form><a href=/pokedex><button type="button" style="background-color:white; font-size:15px" ><b>Main Menu</b></button ></a></form>
	

app/views/pokedex/viewPC.html.erb
<body style="background-color: lightgray;">
<center><h1><%= image_tag "pokebank.jpeg"%> What part of your PC would you like to view?<%= image_tag "pokebank.jpeg"%></h1></center>

<center><%= form_tag do%>
	<br></br>
	<form><a href=/pokemons/viewMyPokemon><button type="button" style="background-color:red; font-size:15px"><b>View my Pokémon</b></button ></a></form>
	<br></br>
	<form><a href=/pokemons/viewMyShiny><button type="button" style="background-color:black; color:white; font-size:15px"><b>View my shiny Pokémon</b></button ></a></form>
	<br></br>
	<form><a href=/pokemons/viewNotCaught><button type="button" style="background-color:black; color:white; font-size:15px" ><b>View Pokémon I have not caught</b></button ></a></form>
	<br></br>
	<form><a href=/pokemons><button type="button" style="background-color:white; font-size:15px" ><b>View All Pokémon</b></button ></a></form>
<%end%></center>

<br></br>
<br></br>
<br></br>
<div align="right"><form><a href=/pokedex><button type="button" style="background-color:white; font-size:15px" ><b>Main Menu</b></button ></a></form>

</body>

app/views/pokemons/_form.html.erb
<%= form_for(@pokemon) do |f| %>
  <% if @pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% @pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Number %><br>
    <%= f.number_field :Number %>
  </div>
  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Type %><br>
    <%= f.text_field :Type %>
  </div>
  <div class="field">
    <%= f.label :Level %><br>
    <%= f.number_field :Level %>
  </div>
  <div class="field">
    <%= f.label :Ability %><br>
    <%= f.text_field :Ability %>
  </div>
  <div class="field">
    <%= f.label :Height %><br>
    <%= f.text_field :Height %>
  </div>
  <div class="field">
    <%= f.label :Weight %><br>
    <%= f.text_field :Weight %>
  </div>
  <div class="field">
    <%= f.label :Gender %><br>
    <%= f.text_field :Gender %>
  </div>
  <div class="field">
    <%= f.label :Caught %><br>
    <%= f.check_box :Caught %>
  </div>
  <div class="field">
    <%= f.label :Location_Caught %><br>
    <%= f.text_field :Location_Caught %>
  </div>
  <div class="field">
    <%= f.label :Level_Caught %><br>
    <%= f.number_field :Level_Caught %>
  </div>
  <div class="field">
    <%= f.label :Shiny %><br>
    <%= f.check_box :Shiny %>
  </div>
  <div class="field">
    <%= f.label :PC %><br>
    <%= f.check_box :PC %>
  </div>
  <div class="field">
    <%= f.label :Can_Evolve %><br>
    <%= f.check_box :Can_Evolve %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<body style="background-color: lightgray;">
<h1>Editing Pokémon</h1>

<%= render 'form' %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/findPokemon.html.erb
<body style="background-color: lightgray;">
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @pokemon.Number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pokemon.Name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @pokemon.Type %>
</p>

<p>
  <strong>Level:</strong>
  <%= @pokemon.Level %>
</p>

<p>
  <strong>Ability:</strong>
  <%= @pokemon.Ability %>
</p>

<p>
  <strong>Height:</strong>
  <%= @pokemon.Height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pokemon.Weight %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @pokemon.Gender %>
</p>

<p>
  <strong>Caught:</strong>
  <%= @pokemon.Caught %>
</p>

<p>
  <strong>Location caught:</strong>
  <%= @pokemon.Location_Caught %>
</p>

<p>
  <strong>Level caught:</strong>
  <%= @pokemon.Level_Caught %>
</p>

<p>
  <strong>Shiny:</strong>
  <%= @pokemon.Shiny %>
</p>

<p>
  <strong>Pc:</strong>
  <%= @pokemon.PC %>
</p>

<p>
  <strong>Can evolve:</strong>
  <%= @pokemon.Can_Evolve %>
</p>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>


<br></br>
<br></br>
<br></br>
<div align="right"><form><a href=/pokedex/viewEntry><button type="button" style="background-color:white; font-size:15px" ><b>Back to View Entry</b></button ></a></form>
<div align="right"><form><a href=/pokedex><button type="button" style="background-color:white; font-size:15px" ><b>Main Menu</b></button ></a></form>

app/views/pokemons/index.html.erb
<body style="background-color: lightgray;"><p id="notice"><%= notice %></p>
<h1>Listing Pokémons</h1>

<table>
  <thead>
    <tr>
      <th> Number </th>
      <th> Name </th>
      <th> Type </th>
      <th> Level </th>
      <th> Ability </th>
      <th> Height </th>
      <th> Weight </th>
      <th> Gender </th>
      <th> Caught </th>
      <th> Location caught </th>
      <th> Level caught </th>
      <th> Shiny </th>
      <th> PC </th>
      <th> Can evolve </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td><%= pokemon.Number %></td>
        <td><%= pokemon.Name %></td>
        <td><%= pokemon.Type %></td>
        <td><%= pokemon.Level %></td>
        <td><%= pokemon.Ability %></td>
        <td><%= pokemon.Height %></td>
        <td><%= pokemon.Weight %></td>
        <td><%= pokemon.Gender %></td>
        <td><%= pokemon.Caught %></td>
        <td><%= pokemon.Location_Caught %></td>
        <td><%= pokemon.Level_Caught %></td>
        <td><%= pokemon.Shiny %></td>
        <td><%= pokemon.PC %></td>
        <td><%= pokemon.Can_Evolve %></td>
        <td><%= link_to 'Show', pokemon %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
        <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pokemon', new_pokemon_path %>

<div align="center"> <%=image_tag "logoBall.jpeg"%></div>
<br></br>
<br></br>
<br></br>
<div align="right"><form><a href=/pokedex><button type="button" style="background-color:white; font-size:15px" ><b>Main Menu</b></button ></a></form>

app/views/pokemons/new.html.erb
<body style="background-color: lightgray;">
<h1>New Pokémon</h1>

<%= render 'form' %>

<%= link_to 'Back', pokemons_path %>


<br></br>
<br></br>
<br></br>
<div align="right"><form><a href=/pokedex/viewEntry><button type="button" style="background-color:white; font-size:15px" ><b>Back to View Entry</b></button ></a></form>
<div align="right"><form><a href=/pokedex><button type="button" style="background-color:white; font-size:15px" ><b>Main Menu</b></button ></a></form>

app/views/pokemons/show.html.erb
<body style="background-color: lightgray;">
<p id="notice"><%= notice %></p>
<div style ="float:right;"><%= image_tag @photo %></div>
<p>
  <strong>Number:</strong>
  <%= @pokemon.Number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pokemon.Name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @pokemon.Type %>
</p>

<p>
  <strong>Level:</strong>
  <%= @pokemon.Level %>
</p>

<p>
  <strong>Ability:</strong>
  <%= @pokemon.Ability %>
</p>

<p>
  <strong>Height:</strong>
  <%= @pokemon.Height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pokemon.Weight %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @pokemon.Gender %>
</p>

<p>
  <strong>Caught:</strong>
  <%= @pokemon.Caught %>
</p>

<p>
  <strong>Location caught:</strong>
  <%= @pokemon.Location_Caught %>
</p>

<p>
  <strong>Level caught:</strong>
  <%= @pokemon.Level_Caught %>
</p>

<p>
  <strong>Shiny:</strong>
  <%= @pokemon.Shiny %>
</p>

<p>
  <strong>Pc:</strong>
  <%= @pokemon.PC %>
</p>

<p>
  <strong>Can evolve:</strong>
  <%= @pokemon.Can_Evolve %>
</p>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/viewMyPokemon.html.erb
<body style="background-color: lightgray;">
<p id="notice"><%= notice %></p>

<center><h1>Your Pokemon </h3></center>

<table>
  <thead>
    <tr>
      <th> Number </th>
      <th> Name </th>
      <th> Type </th>
      <th> Level </th>
      <th> Ability </th>
      <th> Height </th>
      <th> Weight </th>
      <th> Gender </th>
      <th> Caught </th>
      <th> Location caught </th>
      <th> Level caught </th>
      <th> Shiny </th>
      <th> PC </th>
      <th> Can evolve </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%@myPokemon.each do |x|%>
      <tr>
        <td><%= x.Number %></td>
        <td><%= x.Name %></td>
        <td><%= x.Type %></td>
        <td><%= x.Level %></td>
        <td><%= x.Ability %></td>
        <td><%= x.Height %></td>
        <td><%= x.Weight %></td>
        <td><%= x.Gender %></td>
        <td><%= x.Caught %></td>
        <td><%= x.Location_Caught %></td>
        <td><%= x.Level_Caught %></td>
        <td><%= x.Shiny %></td>
        <td><%= x.PC %></td>
        <td><%= x.Can_Evolve %></td>
        <td><%= link_to 'Show', x %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(x) %></td>
        <td><%= link_to 'Destroy', x, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br></br>
<br></br>
<br></br>
<div align="right"><form><a href=/pokedex/viewPC><button type="button" style="background-color:white; font-size:15px" ><b>Back to PC</b></button ></a></form>
<div align="right"><form><a href=/pokedex><button type="button" style="background-color:white; font-size:15px" ><b>Main Menu</b></button ></a></form>

app/views/pokemons/viewMyShiny.html.erb
<body style="background-color: lightgray;">
<p id="notice"><%= notice %></p>

<center><h1>Your Shiny Pokemon </h3></center>

<table>
  <thead>
    <tr>
      <th> Number </th>
      <th> Name </th>
      <th> Type </th>
      <th> Level </th>
      <th> Ability </th>
      <th> Height </th>
      <th> Weight </th>
      <th> Gender </th>
      <th> Caught </th>
      <th> Location caught </th>
      <th> Level caught </th>
      <th> Shiny </th>
      <th> PC </th>
      <th> Can evolve </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%@myShinyPokemon.each do |x|%>
      <tr>
        <td><%= x.Number %></td>
        <td><%= x.Name %></td>
        <td><%= x.Type %></td>
        <td><%= x.Level %></td>
        <td><%= x.Ability %></td>
        <td><%= x.Height %></td>
        <td><%= x.Weight %></td>
        <td><%= x.Gender %></td>
        <td><%= x.Caught %></td>
        <td><%= x.Location_Caught %></td>
        <td><%= x.Level_Caught %></td>
        <td><%= x.Shiny %></td>
        <td><%= x.PC %></td>
        <td><%= x.Can_Evolve %></td>
        <td><%= link_to 'Show', x %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(x) %></td>
        <td><%= link_to 'Destroy', x, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br></br>
<br></br>
<br></br>
<div align="right"><form><a href=/pokedex/viewPC><button type="button" style="background-color:white; font-size:15px" ><b>Back to PC</b></button ></a></form>
<div align="right"><form><a href=/pokedex><button type="button" style="background-color:white; font-size:15px" ><b>Main Menu</b></button ></a></form>

app/views/pokemons/viewNotCaught.html.erb
<body style="background-color: lightgray;">
<p id="notice"><%= notice %></p>

<center><h1>Your Pokemon </h3></center>

<table>
  <thead>
    <tr>
      <th> Number </th>
      <th> Name </th>
      <th> Type </th>
      <th> Level </th>
      <th> Ability </th>
      <th> Height </th>
      <th> Weight </th>
      <th> Gender </th>
      <th> Caught </th>
      <th> Location caught </th>
      <th> Level caught </th>
      <th> Shiny </th>
      <th> PC </th>
      <th> Can evolve </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%@notMyPokemon.each do |x|%>
      <tr>
        <td><%= x.Number %></td>
        <td><%= x.Name %></td>
        <td><%= x.Type %></td>
        <td><%= x.Level %></td>
        <td><%= x.Ability %></td>
        <td><%= x.Height %></td>
        <td><%= x.Weight %></td>
        <td><%= x.Gender %></td>
        <td><%= x.Caught %></td>
        <td><%= x.Location_Caught %></td>
        <td><%= x.Level_Caught %></td>
        <td><%= x.Shiny %></td>
        <td><%= x.PC %></td>
        <td><%= x.Can_Evolve %></td>
        <td><%= link_to 'Show', x %></td>
        <td><%= link_to 'Edit', edit_pokemon_path(x) %></td>
        <td><%= link_to 'Destroy', x, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br></br>
<br></br>
<br></br>
<div align="right"><form><a href=/pokedex/viewPC><button type="button" style="background-color:white; font-size:15px" ><b>Back to PC</b></button ></a></form>
<div align="right"><form><a href=/pokedex><button type="button" style="background-color:white; font-size:15px" ><b>Main Menu</b></button ></a></form>